### ISSUE TITLE
Support EvenSauce version 3

### ISSUE THREAD

**Issue by codedge** [jphooiveld/EventSauceBundle#9]
Eventsauce is currently locked to [version 1](https://github.com/jphooiveld/EventSauceBundle/blob/master/composer.json#L25). Any plans to support the latest major version 3 with this package?

**Comment by jahrralf** [comment]
Just saw this... I will move to https://github.com/eventsauce-symfony/eventsauce-bundle

**Comment by jphooiveld** [comment]
@jahrralf and @codedge, sorry for the late reply. I just upgraded the package to v3. It's still in BETA.

But I would indeed advise to use the the one @jahrralf mentioned (if possible) because it's more up-to-date with new PHP, EventSauce and Symfony Framework features.

I originally created this package to use in our company projects and I will admit that due to time constraints there was no pressing need to update the package until now. I would only use this package if you want to upgrade without too much hassle.
